project:
  type: website
  output-dir: docs
  resources: 
    - "Hutch_CV_2023.pdf"

website:
  title: "Meghan Hutch"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - presentations.qmd
      - teaching.qmd
      - software.qmd
      - blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

