project:
  type: website
  output-dir: docs

website:
  title: "Meghan Hutch"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - presentations.qmd
      - teaching.qmd
      - software.qmd
      - blog.qmd

format:
  html:
    page-layout: full
    grid: 
      body-width: 3000px
      sidebar-width: 50px
      margin-width: 200px
      gutter-width: 0.5rem
    theme: cosmo
    css: styles.css
    toc: true


editor: visual

